---
title: "Other Supporting Resources"
subtitle: "Spring 2022"
output:
  fidelius::html_password_protected:
  password: "aman"
  toc: yes
  toc_float: yes
  theme: flatly
  keep_md: yes
---
<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Review Sheets

[Part 2](\Slides_1110\Part 2_Review.pdf)

[Part 3](\Slides_1110\Part 3_Review.pdf)

[Part 4](\Slides_1110\Part 4_Review.pdf)

## Practice Problems for Quizzes

[Part 1](\Slides_1110\Part 1_Practice_Problems.pdf)

[Part 2](\Slides_1110\Part 2_Practice_Problems.pdf)

[Part 3](\Slides_1110\Part 3_Practice_Problems.pdf)

[Part 4](\Slides_1110\Part 4_Practice_Problems.pdf)

## Final Submission

As a part of the course you will be required to draft a book review or write an essay. The guidelines as well as topics for this final submission are provided below. 

### Book Review

Kindly let me know your choice of the book by **February 14th, 2022**. 

[Topics and Guidelines](\Slides_1110\Book-Review.pdf)

### Essay

Kindly let me know topic of your choice for an essay by **February 14th,2022** via email.

[Topics and Guidelines](\Slides_1110\Essay.pdf)

## Questions you could address in Opinion Writing 

Here are the questions you should be addressing in your opinion writings.

- What is the author saying? 

-  What are their reasons or arguments?

-  Do you agree or disagree with their arguments? (This is where you want to use your knowledge from the class)

- Is there anything you want to add to their arguments or criticize their arguments? (Again, think about what we learned in the course)


